In [2]:
import numpy as np

In [4]:
arr = [[1,2,3], [4,5,6], [6,7,8]]
arr

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [15]:
arr2 = np.array([[1,2,3], [4,5,6], [6,7,8]])

In [17]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
arr2[:2, 1:]


array([[2, 3],
       [5, 6]])

In [61]:
a = np.arange(0,25)

In [62]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
b = a.reshape(5,5)

In [68]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
b[1:,:2]

array([[ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [3]:
import pandas as pd


In [9]:
a = np.random.randn(20).reshape(4,5)

In [10]:
a

array([[-0.43080022,  0.29749483, -0.33892974, -0.31744403,  1.15356836],
       [-1.48926325, -1.43218762,  0.79252588, -0.1741725 , -1.37244134],
       [ 1.87106655,  0.5650656 , -0.3240645 , -1.67291453,  0.85836528],
       [ 0.63907032,  0.9377246 ,  0.2987626 ,  0.01052068,  0.16166121]])

In [11]:
df = pd.DataFrame(a)

In [13]:
df

0         1         2         3         4
0 -0.430800  0.297495 -0.338930 -0.317444  1.153568
1 -1.489263 -1.432188  0.792526 -0.174172 -1.372441
2  1.871067  0.565066 -0.324065 -1.672915  0.858365
3  0.639070  0.937725  0.298763  0.010521  0.161661

In [20]:
df[(df[0]>0) & (df[2]>0)]

0         1         2         3         4
3  0.63907  0.937725  0.298763  0.010521  0.161661

In [21]:
a = np.random.randn(20)

In [24]:
df = pd.DataFrame(a)(hier_index, ['A', 'B'])

TypeError: 'DataFrame' object is not callable

In [23]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [25]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1  0.448412  0.244813
   2 -1.090598 -0.851817
   3  0.414172 -0.733150
G2 1  1.064033  0.258154
   2  1.020031  1.224291
   3  0.903522  2.393437

In [33]:
df.loc['G1'].loc[2, 'A']

-1.090597908332852